// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKwHfhzfYPLVgq0Gleyj99SRDZwxRTNiA',
    appId: '1:963791354047:web:4d9e2973da5e07e0762e0a',
    messagingSenderId: '963791354047',
    projectId: 'sanberapp-3103f',
    authDomain: 'sanberapp-3103f.firebaseapp.com',
    storageBucket: 'sanberapp-3103f.appspot.com',
    measurementId: 'G-QZ76CFK678',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBqIwIXpIDyvsWzZy_EJsQViKmGy-hKjs',
    appId: '1:963791354047:android:0063db240806cd1f762e0a',
    messagingSenderId: '963791354047',
    projectId: 'sanberapp-3103f',
    storageBucket: 'sanberapp-3103f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGheuJrvqSee6Nwu5jIBIe0UIifD37faE',
    appId: '1:963791354047:ios:3a60ace8b91fba6a762e0a',
    messagingSenderId: '963791354047',
    projectId: 'sanberapp-3103f',
    storageBucket: 'sanberapp-3103f.appspot.com',
    iosBundleId: 'com.example.sanberappflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGheuJrvqSee6Nwu5jIBIe0UIifD37faE',
    appId: '1:963791354047:ios:3a60ace8b91fba6a762e0a',
    messagingSenderId: '963791354047',
    projectId: 'sanberapp-3103f',
    storageBucket: 'sanberapp-3103f.appspot.com',
    iosBundleId: 'com.example.sanberappflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKwHfhzfYPLVgq0Gleyj99SRDZwxRTNiA',
    appId: '1:963791354047:web:847d0b8707a8b9c1762e0a',
    messagingSenderId: '963791354047',
    projectId: 'sanberapp-3103f',
    authDomain: 'sanberapp-3103f.firebaseapp.com',
    storageBucket: 'sanberapp-3103f.appspot.com',
    measurementId: 'G-MWEQQBY70L',
  );
}
